### ISSUE TITLE
Extend /var/lib/grafana/plugins/oci-datasource/dist/constants.js with all regions

### ISSUE THREAD

**Issue by martinberger-ch** [oracle/oci-grafana-metrics#103]
Please extend these lines here in file  /var/lib/grafana/plugins/oci-datasource/dist/constants.js with all regions:

 _export('regions', regions = ['ca-toronto-1', 'eu-frankfurt-1', 'uk-london-1', 'us-ashburn-1', 'us-phoenix-1'])

Thanks.

**Comment by huskerdhf** [comment]
Hi @martinberger-ch,

Closing this issue since the oci-grafana-metrics plugin has been updated to include a much more complete list of regions in the referenced source code file as part of the 2.2.4 and 3.0.5 versions of the plugin.

Please try the updated oci-grafana-metrics plugin to determine if your issue was addressed to your satisfaction. Let us know if you believe the issue is still not addressed. If no response is received within 30 days, this issue will be closed.

Thanks
