### ISSUE TITLE
New Singapore Region is not listsed.

### ISSUE THREAD

**Issue by oShyfur** [oracle/oci-grafana-metrics#122]
Hi Team,

Could you please help to add OCI Singapore region in the list. or please guide to how can i connect Singapore region.

Thanks.

**Comment by alexdyas** [comment]
I opened a PR for this - https://github.com/oracle/oci-grafana-metrics/pull/125

**Comment by oShyfur** [comment]
> I opened a PR for this - #125

Thanks 👍

**Comment by huskerdhf** [comment]
Hi @oShyfur,

This issue was addressed in the 3.0.5 version of the metrics plugin.

Please try the updated oci-grafana-metrics plugin to determine if your issue was addressed to your satisfaction. Let us know if you believe the issue is still not addressed. If no response is received within 30 days, this issue will be closed.

Thanks
