### ISSUE TITLE
Use a Single Grafana Instance to monitor multiple OCI tenants

### ISSUE THREAD

**Issue by alxfirst** [oracle/oci-grafana-metrics#18]
Hi team,
We're having a real hard time monitoring multiple tenancies, as so far, we see Grafana uses only the default profile in the .oci config, so you cannot add multiple OCI Datasources to a single Grafana Instance.
Can you please advise how this can be resolved?

**Comment by mickeyboxell** [comment]
Monitoring multiple tenancies may be a challenge because as far as I know OCI was not designed in a way that makes simultaneous multi-tenancy authentication simple. You may be able use the same API keys in multiple tenancies or authenticate with a user that has access to multiple tenancies. In that case you would create a new OCI data source for each of the tenancies from which you are pulling data.

**Comment by alxfirst** [comment]
Wouldn't the OCID of the user be different in the other tenancies, irregardless if they were using the same key?
Using the same key on different tenancies could prove to be a security risk.

From my point of view I would see it as adding a profile selector in the datasource creator, to list which profile from the config file (OCI_CLI) to use. 

https://docs.cloud.oracle.com/iaas/Content/Functions/Tasks/functionsconfigureocicli.htm?Highlight=profile

Any way we could further look into this?

**Comment by revnav** [comment]
Any update on this OCI Team? This is a simple request. We configure multiple OCI tenants in config file using "named" profile and use that in command line to easily switch between tenancies from one command line client..
oci os ns get --profile=<alias in config for tenancy>

how hard it is to get that into oci plugin for grafana? Add one more variable to oci-datasource definition in grafana. That way we can have multiple tenancies monitored from one Grafana server by having one datasource per alias in config file...Common guys move it now :-)

**Comment by chillaxd** [comment]
HI @alxfirst @bongohkim @revnav Please have a look into #106. I have changed it so that it can work multiple profile, cross tenancy policy and it supports Grafana 8 with alerting. It is still on developing phase. But you can have a look and try.
If you need any help or clarification feel free to let me know.

**Comment by kz4d1x** [comment]
Hi, @alxfirst have a look at the https://github.com/oracle/oci-grafana-metrics/releases/tag/v4.0.0 release, it supports the multi-tenancy feature.
