### ISSUE TITLE
LegendFormats details not documented

### ISSUE THREAD

**Issue by kk-hiraskar** [oracle/oci-grafana-metrics#221]
Hi,
[Usage document](https://github.com/oracle/oci-grafana-metrics/blob/master/docs/using.md), only shows few legend formats like `{{resourceDisplayName}}`, `{{metric}}` and few other..
But many of the other format names not able to get from any of the document.

Tried different combinations but not working.

Example:
![image](https://github.com/oracle/oci-grafana-metrics/assets/19647561/fc3c851a-fbd4-4e89-862e-9e10ae94ff23)

This is a "FilesystemUtilization" metrics with "oci-database-cluster" namespace.

Here the last but one field, I can read by DB name with `{{resourceName}}` legend format.
However you can see that same dbSystem can have multiple nodes, so instead of showing multiple same DB name, it is better to display with node name.

Now what is legend format for node name, we don't know!
Not getting from any documents.

Tried many like these, but nothing worked.
{{resourceNodeName}}
{{node}}
{{nodeName}}

Kindly provide full list of legend format names if any where mentioned.

**Comment by mamorett** [comment]
Hi. The legends are documented here: https://github.com/oracle/oci-grafana-metrics/blob/master/docs/using.md, where you can find some examples. The label that can be used as legends are the dimension names, a dimension is a key-value pair that defines the characteristics associated with the metric. For example, resourceId is the OCID of the resource that was scanned. Since each metric has different dimensions names it is not possible to list all of them. You may find useful the OCI documentation. For example this page refers to object storage metrics (oci_objectstorage) and is listing all the dimensions available with that metric: https://docs.oracle.com/en-us/iaas/Content/Object/Reference/objectstoragemetrics.htm?Highlight=metrics. You will find all the available dimensions for each queries in the OCI documentation of each metric emitted by OCI.

**Comment by kk-hiraskar** [comment]
Thanks @mamorett 
Got it.

And any further document on how we can transform data in grafana, as OCI data is very different from Prometheus.
Like some of the problems which i face is in sorting/filtering etc.
