### ISSUE TITLE
Which Grafana version are you using?

### ISSUE THREAD

**Issue by atosrdbms** [oracle/oci-grafana-metrics#229]
Hi all,
I am currently running Grafana 8.5.27 in combination with the 4.1 OCI plugin.
Which versions are you guys using? I prefer to upgrade to version 10, but not sure if things will still work?
Has anybody managed to get Grafana 10 and OCI plugin working?

**Comment by mamorett** [comment]
Hi. We are in the process to release a version of the plugin which will be fully Grafana 10 compatible. Current version is working with Grafana 10 with a limitation. During the datasource configuration is giving an error (due to some rendereing issue in deprecated AngularJS). The error message will look like the following: "Cannot read properties of undefined (reading 'details')". If you got this error you can ignore and move ahead with dashboard creation. As said this is only with Grafana 10 and current version of the plugin.

**Comment by mamorett** [comment]
Plugin version 5.0.0 is released. This version supports Grafana 10.
